services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString

databases:
  - name: flask-db
